/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.gltf 
Author: Foodbird (https://sketchfab.com/Foodbird)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/interdimensional-zen-gallery-space-1bd9d26e53e044eea56a2837ffd75136
Title: Interdimensional zen gallery space
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/model.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
          <group name="54532df5623845c1a999f7c3f0f401d4fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Stones" position={[0, -54.318, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Stones_Stones_0" geometry={nodes.Stones_Stones_0.geometry} material={materials.Stones} />
                </group>
                <group name="Tree" position={[0, 363.099, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Tree_Tree_0" geometry={nodes.Tree_Tree_0.geometry} material={materials.Tree} />
                </group>
                <group name="Leaves" position={[88.934, 111.235, -51.095]} rotation={[-Math.PI / 2, -0.013, 0]} scale={92.675}>
                  <mesh name="Leaves_Tree_0" geometry={nodes.Leaves_Tree_0.geometry} material={materials.Tree} />
                </group>
                <group name="Bushes" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Bushes_Bush_0" geometry={nodes.Bushes_Bush_0.geometry} material={materials.Bush} />
                  <mesh name="Bushes_Tree_0" geometry={nodes.Bushes_Tree_0.geometry} material={materials.Tree} />
                </group>
                <group name="Ground" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Ground_Grond_0" geometry={nodes.Ground_Grond_0.geometry} material={materials.Grond} />
                </group>
                <group name="Water" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Water_Water_0" geometry={nodes.Water_Water_0.geometry} material={materials.Water} />
                </group>
                <group name="Leaves_bollen" position={[731.089, 1289.816, -704.343]} rotation={[-Math.PI / 2, 0.171, 0]} scale={79.854}>
                  <mesh name="Leaves_bollen_Tree_0" geometry={nodes.Leaves_bollen_Tree_0.geometry} material={materials.Tree} />
                </group>
                <group name="Fence" position={[-1190.339, -103.85, 178.397]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Fence_Tree_0" geometry={nodes.Fence_Tree_0.geometry} material={materials.Tree} />
                </group>
                <group name="Woosh_01" position={[-2.477, 443.303, -1296.752]} rotation={[Math.PI, 0, 0]} scale={465.443} />
                <group name="Woosh_02" position={[-2.477, 443.303, -1249.202]} rotation={[0, 0, -Math.PI]} scale={465.443} />
                <group name="Fish" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Armature" position={[-414.125, 147.628, 502.318]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_25">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_27" position={[-2.477, 443.304, -1296.752]} rotation={[Math.PI, 0, 0]} scale={465.443} />
                    <group name="Object_29" position={[-2.477, 443.304, -1249.202]} rotation={[0, 0, Math.PI]} scale={465.443} />
                    <group name="Object_31" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Woosh} skeleton={nodes.Object_28.skeleton} />
                    <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Woosh.012']} skeleton={nodes.Object_30.skeleton} />
                    <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Water.001']} skeleton={nodes.Object_32.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
